<?php

namespace Sites\Admin\Common\StaticPageManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * FragmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FragmentRepository extends SortableRepository
{
}
