parameters:
#    admin_common_static_page_manager.example.class: Sites\Admin\Common\StaticPageManagerBundle\Example

services:
#    admin_common_static_page_manager.example:
#        class: %admin_common_static_page_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
