parameters:
#    admin_common_base.example.class: Sites\Admin\Common\BaseBundle\Example

services:
#    admin_common_base.example:
#        class: %admin_common_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
