parameters:
#    zoo_base.example.class: Sites\Zoo\BaseBundle\Example

services:
#    zoo_base.example:
#        class: %zoo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
